"""Pre-computed commentary cache: render a recorded match's commentary once (slow, on the
local model) and replay it instantly, so playback never waits on the model.

A recorded match's Granite commentary can be pre-rendered: run the stream once, store the
ordered SSE payloads, then replay them paced by their own clock. Live matches don't use
this — there's nothing to pre-render, so they generate on the fly (latency-bound by the
model/hardware). The commentary is still generated by Granite; the cache only stores its
output for a recorded match.
"""
from __future__ import annotations

import json
import re
import time
from pathlib import Path
from typing import Iterator, List, Optional

CACHE_DIR = Path(__file__).resolve().parent.parent / "data" / "cache" / "commentary"


def _slug(text: str) -> str:
    """Filesystem-safe slug for a cache key component."""
    return re.sub(r"[^a-z0-9]+", "-", (text or "").lower()).strip("-") or "x"


def cache_path(match: str, language: str, two_speakers: bool, tts: bool,
               cache_dir=None) -> Path:
    """Where a pre-rendered run is stored (keyed by match, language, and the voice/TTS mode)."""
    base = Path(cache_dir) if cache_dir is not None else CACHE_DIR
    mode = f"{'2v' if two_speakers else '1v'}-{'tts' if tts else 'notts'}"
    return base / f"{_slug(match)}_{_slug(language)}_{mode}.json"


def save_run(match, language, two_speakers, tts, payloads: List[dict], cache_dir=None) -> Path:
    """Persist the ordered SSE payloads of one pre-rendered run."""
    path = cache_path(match, language, two_speakers, tts, cache_dir)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(payloads, ensure_ascii=False, indent=2), encoding="utf-8")
    return path


def load_run(match, language, two_speakers, tts, cache_dir=None) -> Optional[List[dict]]:
    """Return a previously pre-rendered run's payloads, or None if there isn't one."""
    path = cache_path(match, language, two_speakers, tts, cache_dir)
    if not path.exists():
        return None
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
        return data if isinstance(data, list) and data else None
    except Exception:
        return None


def _elapsed_s(payload: dict) -> float:
    """Match-clock seconds for a payload (minute*60 + second)."""
    return float(payload.get("minute", 0)) * 60.0 + float(payload.get("second", 0))


def pace(payloads: List[dict], speed: float = 0.0, sleeper=time.sleep) -> Iterator[dict]:
    """Yield payloads in order, pausing between them by their clock delta / speed.

    ``speed <= 0`` means no waiting (instant playback). This mirrors the live replayer, so
    a cached run honours the Speed slider exactly the way a live run does.
    """
    prev = None
    for payload in payloads:
        if speed and speed > 0 and prev is not None:
            gap = max(0.0, _elapsed_s(payload) - _elapsed_s(prev)) / speed
            if gap > 0:
                sleeper(gap)
        yield payload
        prev = payload
